name: Demo CI/CD Pipeline

on: [push, pull_request]

jobs:
  quality-check:
    name: Lint & Test Stubs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Linting Stub
        run: echo "Running linter... Done!"

  orca-iac_scan:
    name: Orca IaC Scan
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: github_testing # Set the desired project to run the cli scanning with
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Orca IaC Scan
        uses: orcasecurity/shiftleft-iac-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path:
            # scanning directories: ./terraform/ and a file: ./Dockerfile
            "terraform,Dockerfile"


  build-image:
    name: Build Docker Image
    needs: orca-iac_scan # The build ONLY starts if Orca passes!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: |
          docker build -t demo-app:${{ github.sha }} .
          echo "Image built successfully!"
